name: NorthPoleTime
version: '${project.version}'
main: com.villaton.northpoletime.NorthPoleTime
api-version: 1.17
authors: [ Villaton ]
description: Specific Time Changer

commands:
  nptime:
    description: Activates the time.
